package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String formation;

	public Category() {
	}

	public Category(String name, String formation) {
		this.name = name;
		this.formation = formation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFormation() {
		return this.formation;
	}

	public void setFormation(String formation) {
		this.formation = formation;
	}

}
