package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Connection generated by hbm2java
 */
public class Connection implements java.io.Serializable {

	private Integer id;
	private int idUser;
	private String dateLogin;
	private String dateLogOut;

	public Connection() {
	}

	public Connection(int idUser, String dateLogin, String dateLogOut) {
		this.idUser = idUser;
		this.dateLogin = dateLogin;
		this.dateLogOut = dateLogOut;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getDateLogin() {
		return this.dateLogin;
	}

	public void setDateLogin(String dateLogin) {
		this.dateLogin = dateLogin;
	}

	public String getDateLogOut() {
		return this.dateLogOut;
	}

	public void setDateLogOut(String dateLogOut) {
		this.dateLogOut = dateLogOut;
	}

}
