package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Error generated by hbm2java
 */
public class Error implements java.io.Serializable {

	private Integer id;
	private String errorNumber;
	private String message;

	public Error() {
	}

	public Error(String errorNumber, String message) {
		this.errorNumber = errorNumber;
		this.message = message;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getErrorNumber() {
		return this.errorNumber;
	}

	public void setErrorNumber(String errorNumber) {
		this.errorNumber = errorNumber;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
