package com.projetsoap.srcfiles;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message")
public class Message implements java.io.Serializable {

	@Id
	@Column(name="Id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;
	
	@Column(name="Id_Sender")
	private long idSender;
	@Column(name="Id_Receiver")
	private long idReceiver;
	@Column(name="Checked")
	private boolean checked;
	@Column(name="Accepted")
	private boolean accepted;
	@Column(name="Type")
	private String type;
	@Column(name="Id_Mission")
	private long id_mission;
	
	public Message() {
	}

	public Message(long idSender, long idReceiver, boolean checked, boolean accepted, String type, long Id_mission) {
		this.idSender = idSender;
		this.idReceiver = idReceiver;
		this.checked = checked;
		this.accepted = accepted;
		this.type = type;
		this.id_mission = Id_mission;
	}

	public long getId_mission() {
		return id_mission;
	}

	public void setId_mission(long id_mission) {
		this.id_mission = id_mission;
	}

	public long getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public long getIdSender() {
		return this.idSender;
	}

	public void setIdSender(int idSender) {
		this.idSender = idSender;
	}

	public long getIdReceiver() {
		return this.idReceiver;
	}

	public void setIdReceiver(int idReceiver) {
		this.idReceiver = idReceiver;
	}

	public boolean isChecked() {
		return this.checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	public boolean isAccepted() {
		return this.accepted;
	}

	public void setAccepted(boolean accepted) {
		this.accepted = accepted;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
