package com.projetsoap.srcfiles;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name="mission")
public class Mission implements java.io.Serializable {

	@Id
	@Column(name="Id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;
	@Column(name="Title")
	private String title;
	@Column(name="Id_Truck")
	private int idTruck;
	@Column(name="Content")
	private String content;
	@Column(name="Start")
	private String start;
	@Column(name="End")
	private String end;
	@Column(name="Id_Start")
	private int idStart;
	@Column(name="Id_End")
	private int idEnd;
	@Column(name="ShipmentCode")
	private String shipmentCode;

	public Mission() {
	}

	public Mission(String title, int idTruck, String content, String start, String end, int idStart, int idEnd,
			String shipmentCode) {
		this.title = title;
		this.idTruck = idTruck;
		this.content = content;
		this.start = start;
		this.end = end;
		this.idStart = idStart;
		this.idEnd = idEnd;
		this.shipmentCode = shipmentCode;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getIdTruck() {
		return this.idTruck;
	}

	public void setIdTruck(int idTruck) {
		this.idTruck = idTruck;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	public int getIdStart() {
		return this.idStart;
	}

	public void setIdStart(int idStart) {
		this.idStart = idStart;
	}

	public int getIdEnd() {
		return this.idEnd;
	}

	public void setIdEnd(int idEnd) {
		this.idEnd = idEnd;
	}

	public String getShipmentCode() {
		return this.shipmentCode;
	}

	public void setShipmentCode(String shipmentCode) {
		this.shipmentCode = shipmentCode;
	}

}
