package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Modification generated by hbm2java
 */
public class Modification implements java.io.Serializable {

	private Integer idConnection;
	private int idUser;
	private String modificationParameter;
	private String previousValue;
	private String newValue;
	private String modificationDate;

	public Modification() {
	}

	public Modification(int idUser, String modificationParameter, String previousValue, String newValue,
			String modificationDate) {
		this.idUser = idUser;
		this.modificationParameter = modificationParameter;
		this.previousValue = previousValue;
		this.newValue = newValue;
		this.modificationDate = modificationDate;
	}

	public Integer getIdConnection() {
		return this.idConnection;
	}

	public void setIdConnection(Integer idConnection) {
		this.idConnection = idConnection;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getModificationParameter() {
		return this.modificationParameter;
	}

	public void setModificationParameter(String modificationParameter) {
		this.modificationParameter = modificationParameter;
	}

	public String getPreviousValue() {
		return this.previousValue;
	}

	public void setPreviousValue(String previousValue) {
		this.previousValue = previousValue;
	}

	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public String getModificationDate() {
		return this.modificationDate;
	}

	public void setModificationDate(String modificationDate) {
		this.modificationDate = modificationDate;
	}

}
