package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer id;
	private String title;

	public Role() {
	}

	public Role(String title) {
		this.title = title;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
