package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Sector generated by hbm2java
 */
public class Sector implements java.io.Serializable {

	private Integer id;
	private String name;
	private String positionX;
	private String positionY;

	public Sector() {
	}

	public Sector(String name, String positionX, String positionY) {
		this.name = name;
		this.positionX = positionX;
		this.positionY = positionY;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPositionX() {
		return this.positionX;
	}

	public void setPositionX(String positionX) {
		this.positionX = positionX;
	}

	public String getPositionY() {
		return this.positionY;
	}

	public void setPositionY(String positionY) {
		this.positionY = positionY;
	}

}
