package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Start generated by hbm2java
 */
public class Start implements java.io.Serializable {

	private Integer id;
	private String localisation;
	private String name;
	private String quality;
	private String receptionNumber;

	public Start() {
	}

	public Start(String localisation, String name, String quality, String receptionNumber) {
		this.localisation = localisation;
		this.name = name;
		this.quality = quality;
		this.receptionNumber = receptionNumber;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLocalisation() {
		return this.localisation;
	}

	public void setLocalisation(String localisation) {
		this.localisation = localisation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	public String getReceptionNumber() {
		return this.receptionNumber;
	}

	public void setReceptionNumber(String receptionNumber) {
		this.receptionNumber = receptionNumber;
	}

}
