package com.projetsoap.srcfiles;
// Generated 6 janv. 2017 13:37:08 by Hibernate Tools 5.2.0.CR1

/**
 * Truck generated by hbm2java
 */
public class Truck implements java.io.Serializable {

	private Integer id;
	private String brand;
	private String model;
	private int idCompany;
	private int idCategory;
	private String localisationX;
	private String localisationY;
	private int idUser;
	private String state;
	private String function;

	public Truck() {
	}

	public Truck(String brand, String model, int idCompany, int idCategory, String localisationX, String localisationY,
			int idUser, String state, String function) {
		this.brand = brand;
		this.model = model;
		this.idCompany = idCompany;
		this.idCategory = idCategory;
		this.localisationX = localisationX;
		this.localisationY = localisationY;
		this.idUser = idUser;
		this.state = state;
		this.function = function;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public int getIdCompany() {
		return this.idCompany;
	}

	public void setIdCompany(int idCompany) {
		this.idCompany = idCompany;
	}

	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

	public String getLocalisationX() {
		return this.localisationX;
	}

	public void setLocalisationX(String localisationX) {
		this.localisationX = localisationX;
	}

	public String getLocalisationY() {
		return this.localisationY;
	}

	public void setLocalisationY(String localisationY) {
		this.localisationY = localisationY;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

}
